trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install cypress --save-dev
    npx cypress install
    npx cypress run
  displayName: 'Install Cypress'

